name: Continuous Integeration Workflow

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Run Linter and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout Repository

      - name: Installing Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint:check

      - name: Build The Project
        run: npm run build
